// Bundles the third-party code texel ships into the plugin, as plain ES
// modules a hooks module can import: no dynamic import, no require, each file
// under the 1 MiB a hooks module may import. Each library is bundled from an
// entry of texel's own in scripts/, which says what of it texel uses, into a
// vendor folder with its licence, a note of where it came from, and the
// entry's types.
//
//   npm run build:vendor

import { build } from 'esbuild'
import { copyFileSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { basename, join } from 'node:path'
import ts from 'typescript'

const root = new URL('..', import.meta.url).pathname
const MAX_FILE = 1024 * 1024
const INVISIBLE = /[\u00AD\u200B-\u200F\u2028-\u202E\u2060-\u2064\u2066-\u2069\uFEFF]/g

type Vendor = {
  /** The npm package, and where it is made. */
  pkg: string
  url: string
  /** Who holds its copyright, and its licence, as its LICENSE says. */
  holder: string
  license: string
  /** texel's entry into it, in scripts/. */
  entry: string
  /** Where the bundle goes, in the plugin. */
  out: string
  /** What the entry takes from it, for the note. */
  uses: string
  /** More entry points, each a module of its own (MathJax's fonts). */
  more?: string[]
}

async function vendor({ pkg, url, holder, license, entry, out, uses, more = [] }: Vendor) {
  const dir = join(root, out)
  rmSync(dir, { recursive: true, force: true })
  await build({
    // Paths, and so chunk names, relative to the repository: the same on any checkout.
    absWorkingDir: root,
    entryPoints: [`scripts/${entry}`, ...more],
    bundle: true,
    splitting: true,
    format: 'esm',
    platform: 'neutral',
    mainFields: ['module', 'main'],
    minify: true,
    // Modern JavaScript, so classes stay classes: no helper reaching for
    // __proto__, as code compiled to ES5 carries.
    target: 'es2022',
    // As MathJax compiles itself: a field declared in a class is no field
    // until assigned, so a parent's constructor that sets it keeps its value.
    tsconfigRaw: { compilerOptions: { useDefineForClassFields: false } },
    // Characters as they are, not \u escapes, so every name reads as written.
    charset: 'utf8',
    legalComments: 'none',
    outdir: dir,
    entryNames: '[name]',
    chunkNames: 'chunk-[hash]',
    logLevel: 'warning',
  })

  // What the hooks module may import is checked here, not discovered at load.
  for (const file of readdirSync(dir)) {
    // Characters that draw nothing (zero-width, direction marks) as \u
    // escapes, so a reader sees them; they stand only in strings and
    // regular expressions, where an escape means the same.
    const code = readFileSync(join(dir, file), 'utf8').replace(INVISIBLE, c => `\\u${c.charCodeAt(0).toString(16).padStart(4, '0')}`)
    writeFileSync(join(dir, file), code)
    if (statSync(join(dir, file)).size >= MAX_FILE) throw new Error(`${file} is over 1 MiB`)
    if (/\bimport\s*\(/.test(code)) throw new Error(`${file} imports dynamically`)
    if (/\brequire\s*\(/.test(code)) throw new Error(`${file} requires`)
  }

  // The bundle's types: the entry's exported declarations, as written there.
  const name = basename(entry, '.ts')
  const source = readFileSync(join(root, 'scripts', entry), 'utf8')
  const { outputText, diagnostics } = ts.transpileDeclaration(source, { fileName: entry, compilerOptions: { strict: true } })
  if (diagnostics?.length) throw new Error(ts.formatDiagnostics(diagnostics, { getCanonicalFileName: f => f, getCurrentDirectory: () => root, getNewLine: () => '\n' }))
  writeFileSync(join(dir, `${name}.d.ts`), `// Generated by scripts/build-vendor.mts from scripts/${entry}.\n${outputText.replace(/^import .*\n/gm, '')}`)

  copyFileSync(join(root, 'node_modules', pkg, 'LICENSE'), join(dir, 'LICENSE'))
  const { version } = JSON.parse(readFileSync(join(root, 'node_modules', pkg, 'package.json'), 'utf8'))
  writeFileSync(
    join(dir, 'README.md'),
    `# ${pkg}, bundled

The files here are ${pkg} ${version} (${url}), Copyright ${holder},
licensed under the ${license} (LICENSE here).

They are generated, not edited: \`npm run build:vendor\` bundles the part of it
texel uses (scripts/${entry}: ${uses}) with esbuild into minified ES modules.
texel's own code in scripts/${entry} is MIT like the rest of texel.
`,
  )
  const files = readdirSync(dir)
  const size = files.reduce((sum, f) => sum + statSync(join(dir, f)).size, 0)
  console.log(`${pkg}: ${files.length} files, ${(size / 1024).toFixed(0)} KB in ${out}`)
}

const fonts = 'node_modules/mathjax-full/ts/output/svg/fonts/tex'
await vendor({
  pkg: 'mathjax-full',
  url: 'https://github.com/mathjax/MathJax-src',
  holder: 'The MathJax Consortium',
  license: 'Apache License 2.0',
  entry: 'mathjax-entry.ts',
  out: 'plugin/hooks/render/mathjax/vendor',
  uses: 'TeX input, SVG output and the TeX fonts, one module per font file, built from MathJax\'s TypeScript sources, which convert TeX to an SVG tree',
  more: readdirSync(join(root, fonts)).filter(f => f.endsWith('.ts')).map(f => join(fonts, f)),
})
await vendor({
  pkg: 'fflate',
  url: 'https://github.com/101arrowz/fflate',
  holder: 'Arjun Barrett',
  license: 'MIT License',
  entry: 'fflate-entry.ts',
  out: 'plugin/hooks/render/vendor',
  uses: 'zlib compression for PNGs, and its reverse',
})
