// Bundles the part of MathJax texel uses (scripts/mathjax-entry.ts) into the
// plugin, as plain ES modules a hooks module can import: no dynamic import,
// and each file under the 1 MiB a hooks module may import, so the fonts are
// split one module per font file.
//
//   npm run build:mathjax

import { build } from 'esbuild'
import { copyFileSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import ts from 'typescript'

const root = new URL('..', import.meta.url).pathname
const out = join(root, 'plugin/hooks/render/mathjax/vendor')
const fonts = join(root, 'node_modules/mathjax-full/js/output/svg/fonts/tex')
const MAX_FILE = 1024 * 1024

rmSync(out, { recursive: true, force: true })
await build({
  // Paths, and so chunk names, relative to the repository: the same on any checkout.
  absWorkingDir: root,
  entryPoints: ['scripts/mathjax-entry.ts', ...readdirSync(fonts).filter(f => f.endsWith('.js')).map(f => join('node_modules/mathjax-full/js/output/svg/fonts/tex', f))],
  bundle: true,
  splitting: true,
  format: 'esm',
  platform: 'neutral',
  mainFields: ['module', 'main'],
  minify: true,
  legalComments: 'none',
  outdir: out,
  entryNames: '[name]',
  chunkNames: 'chunk-[hash]',
  logLevel: 'warning',
})

// What the hooks module may import is checked here, not discovered at load.
for (const file of readdirSync(out)) {
  const path = join(out, file)
  const code = readFileSync(path, 'utf8')
  if (statSync(path).size >= MAX_FILE) throw new Error(`${file} is over 1 MiB`)
  if (/\bimport\s*\(/.test(code)) throw new Error(`${file} imports dynamically`)
  if (/\brequire\s*\(/.test(code)) throw new Error(`${file} requires`)
}

copyFileSync(join(root, 'node_modules/mathjax-full/LICENSE'), join(out, 'LICENSE'))
const { version } = JSON.parse(readFileSync(join(root, 'node_modules/mathjax-full/package.json'), 'utf8'))
writeFileSync(
  join(out, 'README.md'),
  `# MathJax, bundled

The files here are MathJax ${version} (https://github.com/mathjax/MathJax-src,
npm \`mathjax-full\`), Copyright The MathJax Consortium, licensed under the
Apache License 2.0 (LICENSE here).

They are generated, not edited: \`npm run build:mathjax\` bundles the part of
MathJax texel uses (scripts/mathjax-entry.ts: TeX input, SVG output, the TeX
fonts) with esbuild into minified ES modules, one per font file. texel's own
code in scripts/mathjax-entry.ts, which converts TeX to an SVG tree, is MIT
like the rest of texel.
`,
)
// The bundle's types: the entry's exported declarations, as written there.
const entry = readFileSync(join(root, 'scripts/mathjax-entry.ts'), 'utf8')
const { outputText, diagnostics } = ts.transpileDeclaration(entry, { fileName: 'mathjax-entry.ts', compilerOptions: { strict: true } })
if (diagnostics?.length) throw new Error(ts.formatDiagnostics(diagnostics, { getCanonicalFileName: f => f, getCurrentDirectory: () => root, getNewLine: () => '\n' }))
writeFileSync(join(out, 'mathjax-entry.d.ts'), `// Generated by scripts/build-mathjax.mts from scripts/mathjax-entry.ts.\n${outputText.replace(/^import .*\n/gm, '')}`)
const files = readdirSync(out)
const size = files.reduce((sum, f) => sum + statSync(join(out, f)).size, 0)
console.log(`mathjax: ${files.length} files, ${(size / 1024 / 1024).toFixed(1)} MB in ${out}`)
