// Bundles the part of MathJax texel uses (scripts/mathjax-entry.ts) into the
// plugin, as plain ES modules a hooks module can import: no dynamic import,
// and each file under the 1 MiB a hooks module may import, so the fonts are
// split one module per font file.
//
//   npm run build:mathjax

import { build } from 'esbuild'
import { copyFileSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = new URL('..', import.meta.url).pathname
const out = join(root, 'plugin/hooks/render/mathjax/vendor')
const fonts = join(root, 'node_modules/mathjax-full/js/output/svg/fonts/tex')
const MAX_FILE = 1024 * 1024

rmSync(out, { recursive: true, force: true })
await build({
  entryPoints: [join(root, 'scripts/mathjax-entry.ts'), ...readdirSync(fonts).filter(f => f.endsWith('.js')).map(f => join(fonts, f))],
  bundle: true,
  splitting: true,
  format: 'esm',
  platform: 'neutral',
  mainFields: ['module', 'main'],
  minify: true,
  legalComments: 'none',
  outdir: out,
  entryNames: '[name]',
  chunkNames: 'chunk-[hash]',
  logLevel: 'warning',
})

// What the hooks module may import is checked here, not discovered at load.
for (const file of readdirSync(out)) {
  const path = join(out, file)
  const code = readFileSync(path, 'utf8')
  if (statSync(path).size >= MAX_FILE) throw new Error(`${file} is over 1 MiB`)
  if (/\bimport\s*\(/.test(code)) throw new Error(`${file} imports dynamically`)
  if (/\brequire\s*\(/.test(code)) throw new Error(`${file} requires`)
}

copyFileSync(join(root, 'node_modules/mathjax-full/LICENSE'), join(out, 'LICENSE'))
writeFileSync(
  join(out, 'mathjax-entry.d.ts'),
  `// Generated by scripts/build-mathjax.mts: the bundle's types, from scripts/mathjax-entry.ts.
export type SvgNode = { tag: string; attrs: Record<string, string>; children: SvgNode[] }
export type TexResult = SvgNode | { error: string }
export type Tex = { convert(tex: string, display: boolean): TexResult }
export declare function createTex(macros: string): Tex
`,
)
const files = readdirSync(out)
const size = files.reduce((sum, f) => sum + statSync(join(out, f)).size, 0)
console.log(`mathjax: ${files.length} files, ${(size / 1024 / 1024).toFixed(1)} MB in ${out}`)
